### ISSUE TITLE
❓Question: is it possible to add global links not connected to any project?

### ISSUE THREAD

**Issue by Adam-it** [estruyf/vscode-squarl#1]
Hi 👋
I was wondering. Currently when I add some link the extensions stores that info in the setting.json file. Is it possible to add some link which are like 'global' so does not matter which workspace/project I have opened I will always see them in the extension?

**Comment by estruyf** [comment]
Hi @Adam-it this indeed the plan, but the current preview version does not yet support it.

**Comment by Adam-it** [comment]
> Hi @Adam-it this indeed the plan, but the current preview version does not yet support it.

That would be awesome 👍👍.
Any ideas on how you would like this to be handled? 
Are you open for co contributions? I am quite full this and next week when it comes for open source time but if in 3 weeks time this will be still open and you have more important stuff to do maybe I could give it a shot and try to help out?

**Comment by estruyf** [comment]
I already had some things in progress for this that were not yet committed. Think in the end. There will be three sections: 

- Global
- Project
- Team (squarl.json)

I'll already push the code to make the global bookmarks available, it will look as follows:

![Xnapper-2022-08-29-10 53 01](https://user-images.githubusercontent.com/2900833/187163215-48dc3684-31c5-4d54-a4bd-ae71b8db97d5.png)

Things that are still missing to make the feature complete are:

- [x] Creating the bookmark automatically in the global settings.json file (at the moment, this is manual)
- [x] Creating the group automatically in the global settings.json file
- [ ] Promote/demote link from project to global (and vice versa)
- [x] Search through global/project/team links. At the moment, only project and team links are supported

PS: you are always free to contribute 🤓

**Comment by Adam-it** [comment]
ok. Great news 👍. All of those seem like perfect task to be taken 😊. 
I will mark this comment and get back to you in 3 weeks what maybe is still on the plate so if you want we could split the left work 💪.
Thanks for your quick response 👍
have a awesome week and will be in touch 🤩

**Comment by Adam-it** [comment]
@estruyf so I would like to refresh the topic. 
Is there anything particular you are working on but don't have time and would like to share work ?

**Comment by estruyf** [comment]
Most of the functionality is already included. The only thing that is open is to promote/demote the items from global to local and back.

**Comment by Adam-it** [comment]
ok so if you would be willing to share work I could try to implement this one 🤔. 
If you agree I would open a separate issue for it and there we could clarify this functionality in a bit more detail so I would do/implement it in a way you want....  and close this issue 

But if I understand the feature correctly I should add two links to the context menu of the link item:
- promote - which will allow to upgrade link from local project to global
- demote - which will downgrade the link from global to local
mockup:
![image](https://user-images.githubusercontent.com/58668583/191219728-52ed2d08-9f40-4ff1-8203-592e7e735ccf.png)

questions:
- should we allow to pick group when promoting/demoting?
- should we allow to rename the link along the way? I was thinking that the process could be actually like deleting one link in one area and adding a new link in new area with prefilled values from the old link (name, link, description) 🤔

**Comment by estruyf** [comment]
You are completely free to implement this one.

- The **promote** action should only appear for project bookmarks, so they become global bookmarks.
- The **demote** action should only appear for global bookmarks, so they can be put on the local level.

Does this make sense?

> should we allow to pick group when promoting/demoting?

Yes, as groups can be different on project and global level.

> should we allow to rename the link along the way? I was thinking that the process could be actually like deleting one link in one area and adding a new link in new area with prefilled values from the old link (name, link, description) 🤔

The bookmark needs to be deleted and recreated indeed, but apart from asking to which group it needs to be recreated, I wouldn't ask for description or link changes.

**Comment by Adam-it** [comment]
thanks @estruyf for the opportunity 🤩. I feel like I will learn a lot even implementing such a small functionality 👍
I will create a separate issue for it today during night and start working over the weekend 👍. 
closing this one 👍
