### ISSUE TITLE
Bookmarks lost and overridden

### ISSUE THREAD

**Issue by abulka** [estruyf/vscode-squarl#5]
When I create a new bookmark I sometimes have the old bookmarks clobbered and lost.

Lucky I have my `squarl.bookmarks` file in source control, so I can repair things manually. 

For example running `Squarl: Bookmark file` command and answering:
    
    No (workspace settings)
    entering a description
    choose a group with arrows
    yes to highlight

resulted in losing all my bookmarks when the latest one was added.

![image](https://github.com/estruyf/vscode-squarl/assets/11467530/0c5e5a0e-c667-432d-82bc-85ee35da2f42)

This has happened multiple times on multiple machines running vscode on Mac. It is intermittent.

**Comment by estruyf** [comment]
Thanks @abulka, I found the issue and fixed it in version `v1.1.1`. Let me know if this fixed the issue on your end as well.
